### PR TITLE
[NFC]Print reverting scheduling message with logger to allow printing in release

### PR DESCRIPTION
**Pull request by VladM1076**
Reverting scheduling statement will now appear in release build.
Vang and I believe this statement is important to print in release to provide a more detailed scheduler output without needing to run the slower debug build.

### CODE REVIEW

**Comment by vangthao95** [comment]
I believe this is an important log to print because it basically means the scheduling has failed for the particular region and we must change how we handle it in our compile-time statistics.

**Comment by Quincunx271** [comment]
As an aside, what is NFC?

**Comment by VladM1076** [comment]
[NFC] -> No Functional Changes

**Comment by vangthao95** [comment]
It is part of the LLVM lexicon: https://github.com/llvm/llvm-project/blob/master/llvm/docs/Lexicon.rst

**Pull request merged**
