### PR TITLE
Amdgpu superbuild

### PR DESCRIPTION
**Pull request by Quincunx271**
This adds a superbuild script for the AMD GPU (Optimizer-amd) machine.

There is a problem which I have been unable to work out; perhaps someone has an idea what's causing it: After configuring, you have to repeatedly run `make -j32`, ignoring the errors, until it succeeds. The `.inc` files generated by tablegen don't seem to have their dependencies set up correctly, but I have been unable to debug why this is the case.

### CODE REVIEW

**Comment by Quincunx271** [comment]
These latest commits fix the issue. This now works for building on the AMDGPU.

**Comment by vangthao95** [comment]
Is this ready to be merged in? If it is then it looks good to me.

**Comment by Quincunx271** [comment]
Now it should be ready to merge. I'd need to write a descriptive commit message when I squash, but it should be functionally ready.

**Comment by Quincunx271** [comment]
I found another kink to work out: sometimes when OptSched files are changed, `make` doesn't rebuild. Instead, you have to navigate to the ROCm-build directory and kick off `make` yourself.

**Comment by Quincunx271** [comment]
Closing this for now. I see this as superseded by #86

**Pull request closed without merging**
