### PR TITLE
Add .clang-format and .clang-tidy

### PR DESCRIPTION
**Pull request by kerbowa**
Add code style/linter configuration files.

### CODE REVIEW

**Comment by kerbowa** [comment]
Would add mfdorst as reviewer but needs to be part of CSUS_LLVM.

**Comment by mfdorst** [comment]
Your `.clang-format` file is empty - I believe you want to run
```
clang-format -style=llvm -dump-config > .clang-format
```

**Comment by mfdorst** [comment]
But then again, since we're just using LLVM style, we can just run
```
clang-format -i -style=llvm **/*.cpp **/*.h
```
so the file may not be necessary. I was thinking of just making a tiny script for that to make it easier for others, something like `clang-tidy.sh` and we can have everyone run that before committing.

**Comment by kerbowa** [comment]
I see `BasedOnStyle: LLVM`, which is equivalent to `-style=llvm`.

**Comment by mfdorst** [comment]
Is it? You may be right. I assumed that was just a comment. LGTM.

**Pull request merged**
