### PR TITLE
Refactor Graph / LinkedList

### PR DESCRIPTION
**Pull request by Quincunx271**
Adds C++ STL style iterators to LinkedList. Adds some accessors and adds a way to remove edges.

### CODE REVIEW

**Comment by Quincunx271** [comment]
This PR is ready for review. I do not intend to squash any of the commits, so let me know in the review if you think some should be squashed.

**Review by paul-mchugh — APPROVED** [review]
LGTM,

My only note is that I object to the use of linked lists in general, since they are cache inefficient (Including this one that is normally sorted since the size of an entry is 24 bytes, so only 2.66 entries fit in a 64 byte cache line as opposed to 8 pointers that fit in a 64 byte cache line).  Should the use of linked lists prove necessary, then at some time in the future we should replace our Linked List with an std::list.

I realize that now is not an appropriate time to remove all linked lists, or replace them with std::list.

**Review by VladM1076 — APPROVED** [review]
LGTM

**Comment by Quincunx271** [comment]
@paul-mchugh I'll link this with #116 just to connect the conversations; I agree with you. I will merge this, but it would be a good idea to remove this custom data structure, and it would be a good idea to remove the linked-list altogether if possible.

**Pull request merged**
