### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by mfdorst**
Clarify which steps are for Ubuntu and which are for MacOS

### CODE REVIEW

**Comment by kerbowa** [comment]
Is there anything special steps to build on MacOS if you don't want to use xcode?

**Comment by kerbowa** [comment]
I think it's better if maybe the README has general info and we can also have install-linux/install-MacOS as separate documents. What do you think?

**Comment by mfdorst** [comment]
That's a good question. It didn't occur to me to try, but I guess the instructions for building on Ubuntu should work on MacOS, provided you install `cmake` first. I was already planning on setting it up in CLion and providing alternate instructions for that - I can add building without any IDE to my todo list.

I think that's a good idea. So basically, remove the "quick start guide" from README and add two more specific readme's, perhaps `README-Ubuntu` and `README-MacOS`? And we can replace the guide with links to the different readme's. And I think I'll just copy the duplicate instructions into the MacOS readme so all the directions will be in one place.

**Comment by kerbowa** [comment]
I agree that having some duplication is okay; it will be easier to read. We could have have one INSTALL.md which is linked in the main README like in most of our ROCm repos i.e. https://github.com/ROCm-Developer-Tools/HIP

**Comment by mfdorst** [comment]
Okay. So move the quick-start guide to `INSTALL.md`, which will (for now) have an Ubuntu section and a MacOS section. And we will link to `INSTALL.md` in `README.md`. Sound good?

**Pull request closed without merging**
