### PR TITLE
Add notes on static superiority lecture

### PR DESCRIPTION
**Pull request by Quincunx271**
I figure that it makes more sense to document lectures in the repository than in the GitHub Wiki pages.

### CODE REVIEW

**Comment by kerbowa** [comment]
Are you sure you want to detail this publicly if it's unpublished work?

**Comment by Quincunx271** [comment]
I didn't see the problem with that.... Is that something we want to avoid?

**Comment by vangthao95** [comment]
I think we should get the permission of Dr. Shobaki first to post this publicly.

**Comment by Quincunx271** [comment]
It's a bit strange to me, as it's already posted in the code and commented in the code, but okay.

**Pull request closed without merging**
