### PR TITLE
Added documentations on how to build flang, scripts for CPU2006, and patches for LLVM6.

### PR DESCRIPTION
**Pull request by vangthao95**

### CODE REVIEW

**Comment by kerbowa** [comment]
Is the runspec wrapper an updated version, or the same that is already in the scripts folder?

**Comment by vangthao95** [comment]
I have updated it to also print the weighted spills.

**Comment by kerbowa** [comment]
> I have updated it to also print the weighted spills.

Can you delete the old one then? I think weighted spills are always printed when we use the wrapper.

Would you please rename the documentations directory to documentation. Thanks.

**Comment by kerbowa** [comment]
We could just rename SPEC -> CPU2006 and then replace the old runspec wrapper in that directory.

**Comment by kerbowa** [comment]
LGTM

**Pull request merged**
