### PR TITLE
Clang-tidy and indentation fix

### PR DESCRIPTION
**Pull request by mfdorst**
**Warning! This branch has a huge number of changes because I fixed the indentation on every source file in the project.** Basically anyone who's working on anything right now is going to have trouble merging after this commit.

#9

### CODE REVIEW

**Comment by mfdorst** [comment]
For whatever reason when I fix the indentation of files it sometimes leaves comments completely unindented. I don't have the patience to search through every file for that so if people could fix those issues when they find them that'd be cool

**Comment by kerbowa** [comment]
This is incorrect indentation and doesn't follow the LLVM conventions.

**Comment by mfdorst** [comment]
I can't seem to get `clang-tidy` working on this project. My editor provides contextual clang-tidy warnings, but I can't figure out how to run the command on its own.
`clang-format` works, but I don't know if the default format rules are the right ones - do you have a configuration file for clang-format too?

**Comment by kerbowa** [comment]
There is a clang-format config file in the same repo. I just use 'clang-format -style=llvm'. Can you just copy the dot file to the reop and run clang-tidy from the command line?

**Comment by mfdorst** [comment]
clang-tidy works by basically compiling the whole source tree. So in general you have to pass it the same commands you give your compiler. CMake obviously complicates that, but you can have CMake generate a "compilation database" which tells clang-tidy how to compile your code. I tried generating a compilation database for just the OptSched target, but it doesn't seem to like that. For now I'm just gonna switch to clang-format until I can figure out how to work with clang-tidy.

**Comment by kerbowa** [comment]
https://github.com/CSUS-LLVM/OptSched/blob/c980bbf445e14111404ab20ccb018a68dd03e042/CMakeLists.txt#L24

I added compilation db by default already. I'm pretty sure llvm does the same. I think maybe it's your ide that's wonky, can't really help you there.

**Comment by mfdorst** [comment]
Hold up don't merge this just yet, I managed to delete `aco.cpp`

**Comment by kerbowa** [comment]
Was going to ask :)

I think I will take a closer look tomorrow. Why is it marking some class methods as static?

**Comment by mfdorst** [comment]
Is clang-format doing that? Or are you asking about the earlier clang-tidy commits?

**Comment by mfdorst** [comment]
clang-tidy does sometimes recommend a method be static - I think I only made that change once though - I'll take a closer look in case that was a bad idea.

**Comment by kerbowa** [comment]
I think some things from clang-tidy are still here like, adding override for example.

**Comment by mfdorst** [comment]
The last two commits have no clang-tidy fixes. The previous ones do, with the exception of 'Fix indentation project-wide'.

**Comment by mfdorst** [comment]
Do you want me to make a pull request with _only_ clang-format changes, and a different one for clang-tidy changes?

**Comment by mfdorst** [comment]
Actually I like that idea. I will do that tomorrow - I have math homework to do right now.

**Comment by mfdorst** [comment]
Closing this. #18 runs clang-format for the whole project. If that gets merged, I'll rebase these changes on top of those which should make everything cleaner and easier to follow.

**Pull request closed without merging**
